# Generated by Django 6.0.3 on 2026-05-03 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('group', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('default_action', models.CharField(choices=[('keep', 'Keep'), ('archive', 'Archive'), ('trash', 'Trash')], default='keep', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('current_role', models.CharField(choices=[('student', 'Student'), ('job_seeker', 'Job Seeker'), ('working_pro', 'Working Professional'), ('hr', 'HR / Recruiter'), ('manager', 'Manager / Leadership'), ('freelancer', 'Freelancer / Consultant'), ('entrepreneur', 'Entrepreneur / Founder'), ('other', 'Other')], default='other', max_length=32)),
                ('current_position', models.CharField(blank=True, help_text='e.g. Software Engineer at XYZ', max_length=200)),
                ('education', models.TextField(blank=True, help_text='Degrees, schools, fields')),
                ('experience', models.TextField(blank=True, help_text='Brief summary of past work')),
                ('skills_interests', models.TextField(blank=True)),
                ('email_type', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('mixed', 'Mixed')], default='mixed', max_length=16)),
                ('additional_context', models.TextField(blank=True, help_text='Anything else the AI should know')),
                ('onboarded', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('important_categories', models.ManyToManyField(blank=True, related_name='users_who_care', to='accounts.emailcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassifiedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_id', models.CharField(max_length=64)),
                ('thread_id', models.CharField(blank=True, max_length=64)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('sender', models.CharField(blank=True, max_length=300)),
                ('snippet', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('importance', models.IntegerField(default=3)),
                ('reason', models.TextField(blank=True)),
                ('action_taken', models.CharField(default='kept', max_length=16)),
                ('is_event', models.BooleanField(default=False)),
                ('event_when', models.CharField(blank=True, max_length=120)),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_emails', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.emailcategory')),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-received_at'], name='accounts_cl_user_id_d1b2f3_idx')],
                'unique_together': {('user', 'gmail_id')},
            },
        ),
    ]
