# Generated by Django 6.0.3 on 2026-05-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailcategory_userprofile_classifiedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedemail',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classifiedemail',
            name='sender_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='classifiedemail',
            name='unsubscribe_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='emailcategory',
            name='short_label',
            field=models.CharField(default='exit', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blocked_senders',
            field=models.TextField(blank=True, help_text='One email/domain per line — auto-trashed'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='industries',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='live_classification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='org_domain',
            field=models.CharField(blank=True, help_text='e.g. acme.com — emails from this domain get the MyOrg label.', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_roles',
            field=models.TextField(blank=True, help_text='(Job seekers) What roles are you targeting?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='additional_context',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_position',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.TextField(blank=True),
        ),
    ]
