# Generated by Django 6.0.3 on 2026-05-26 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_classifiedemail_is_urgent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcategory',
            name='default_action',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='important_categories',
        ),
        migrations.AddField(
            model_name='emailcategory',
            name='default_tier',
            field=models.CharField(choices=[('critical', '🔥 Critical'), ('important', '⭐ Important'), ('normal', '📌 Normal'), ('low', '📥 Low'), ('ignore', '🗑️ Ignore')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blocked_senders',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_role',
            field=models.CharField(choices=[('student', 'Student'), ('job_seeker', 'Job Seeker'), ('working_pro', 'Working Professional'), ('hr', 'HR / Recruiter'), ('manager', 'Manager / Leadership'), ('freelancer', 'Freelancer / Consultant'), ('sales', 'Sales'), ('support', 'Customer Support'), ('entrepreneur', 'Entrepreneur / Founder'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='org_domain',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_roles',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='UserCategoryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('critical', '🔥 Critical'), ('important', '⭐ Important'), ('normal', '📌 Normal'), ('low', '📥 Low'), ('ignore', '🗑️ Ignore')], max_length=16)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.emailcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
